apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
data:
  SPRING_APPLICATION_NAME: "{{ .Values.properties.application.name }}"
  SPRING_CACHE_REDIS_TIME_TO_LIVE: "{{ .Values.properties.redis.cache.ttl }}"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.properties.datasource.host }}:{{ .Values.properties.datasource.port }}/{{ .Values.properties.datasource.database }}"
  SPRING_DATA_REDIS_HOST: "{{ .Values.properties.redis.host }}"
  SPRING_DATA_REDIS_PORT: "{{ .Values.properties.redis.port }}"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://{{ .Values.properties.eureka.host }}:{{ .Values.properties.eureka.port }}/eureka/"