apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
spec:
  selector:
    app: "{{ .Chart.Name }}-service"
  ports:
    - protocol: TCP
      port: {{ .Values.properties.application.port }}
      targetPort: 8080
  type: ClusterIP
  