apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
data:
  SPRING_APPLICATION_NAME: "{{ .Values.properties.application.name }}"
  SPRING_CACHE_REDIS_TIME_TO_LIVE: "{{ .Values.properties.redis.cache.ttl }}"