apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
spec:
  selector:
    app: "{{ .Release.Name }}-service"
  ports:
    - protocol: TCP
      port: "{{ .Values.properties.app.port }}"
      targetPort: 8080
  type: ClusterIP
  