replicaCount: 1

image:
  name:
  tag:

secret:
  name: "category-app-secret"
  keys:
    postgresUsername: "postgresUsername"
    postgresPassword: "postgresPassword"
    redisPassword: "redisPassword"

properties:
  application:
    name: category-app
    port: 8080
  redis:
    cache:
      ttl: "7d"
    host: redis-master
    port: 6379
  datasource:
    host: postgres-postgresql
    port: 5432
    database: category-app