replicaCount: 1

image:
  name:
  tag:

secret:
  name: "category-app-secret"
  keys:
    postgresUsername: "postgresUsername"
    postgresPassword: "postgresPassword"
    redisPassword: "redisPassword"

properties:
  application:
    name: category-app
    port: 8080
    eureka:
      hostname: category-app-service.category-app.svc.cluster.local
  redis:
    cache:
      ttl: "7d"
    host: redis-master
    port: 6379
  datasource:
    host: postgresql
    port: 5432
    database: category_app
  eureka:
    host: eureka-server-service.eureka-server.svc.cluster.local
    port: 8761