replicaCount: 1

image:
  name:
  tag:

secret:
  name: "category-app-secret"
  keys:
    postgresUsername: "postgresUsername"
    postgresPassword: "postgresPassword"
    redisPassword: "redisPassword"

properties:
  application:
    name: "category-service"
    port: 8080
  redis:
    cache:
      ttl: "7d"
    host:
    port:
  datasource:
    host:
    port:
    database: